### ISSUE TITLE
Staff topic reminders are non-descript

### ISSUE THREAD

**Issue by cmo-hms** [HMSAB/discourse-stale-topics#1]
Client topic reminders may also be.

For staff topic reminders the subject is "A topic requires attention". The body is Hello staff,
This topic 2 was created 2 hours ago and has not received a response.
This is the 0th time a notification is being sent for this topic.

Please check this topic as soon as possible."

It would be helpful if the subject of the reminders was based on the topic subject. Something like "{topic subject} requires attention", and in the body changing the link to the topic to show the topic subject as well. Otherwise all of the reminders blend together with no way to tell them apart.

**Comment by joseanor** [comment]
@cmo-hms 

Fixed per: https://github.com/HMSAB/discourse-stale-topics/commit/21740fbe1eed422c42af9d6f5fa359c2d630de77

**Comment by cmo-hms** [comment]
Very cool!

On Apr 26, 2018, at 11:50 AM, Jordan Seanor <notifications@github.com<mailto:notifications@github.com>> wrote:


@cmo-hms<https://github.com/cmo-hms>

Fixed per: 21740fb<https://github.com/HMSAB/discourse-stale-topics/commit/21740fbe1eed422c42af9d6f5fa359c2d630de77>
